openapi: '3.0.0'
info:
  version: '1.0.0'
  title: 'Orders API'
  description: API для Заказов по курсу Архитектура программных систем
servers:
  - url: http://localhost:8081
    description: Example server
paths:
  /search:
    get:
      summary: Поиск Заказов по маске ID пользователя
      responses:
        '200':
          description: The orders for the provided masks
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/order'
        404:
          description: No user found for the provided mask
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        500:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /order:
    post:
      summary: Добавление услуги в заказ
      parameters:
      - name: service_id
        description: идентификатор услуги
        in: query
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: Идентификатор, добавленного заказа
          content:
            application/json:
              schema:
                type: integer
        404:
          description: Ошибка добавления заказа
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        500:
          description: Неожиданная ошибка
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    order_id:
      description: Уникальный идентификатор заказа
      type: integer
    orders:
      type: array
      items:
        $ref: '#/components/schemas/order'
    order:
      type: object
      required:
        - id
        - user_id
        - service_id
      properties:
        id:
          $ref: '#/components/schemas/order_id'
        user_id:
          type: integer
        service_id:
          type: integer
    Error:
      type: object
      required:
        - message
      properties:
        message:
          description: Сообщение о ошибке
          type: string
  securitySchemes:
      basicAuth:     
        type: http
        scheme: basic
security:
  - basicAuth: []